Test new env New LICENSE

diff --git a/hooks/post_checkout b/hooks/post_checkout
--- a/hooks/post_checkout
+++ b/hooks/post_checkout
@@ -1,16 +1,28 @@
 #!/bin/bash
 
-BUILD_ARCH=$(echo "${DOCKERFILE_PATH}" | rev | cut -d '.' -f 2 | rev)
+# Cycle trough the the arches
+for DEST_BUILD_ARCH in ${DEST_ARCHES}
+do
+    if [ ${DEST_BUILD_ARCH} == "amd64" ]; then
+        echo 'qemu-user-static: Download not required for amd64'
+        continue
+    elif [ ${DEST_BUILD_ARCH} == "arm32v7" ]; then
+        QEMU_USER_STATIC_ARCH="arm"
+    elif [ ${DEST_BUILD_ARCH} == "arm64v8" ]; then
+        QEMU_USER_STATIC_ARCH="aarch64"
+    else 
+        echo "DEBUG: DEST_BUILD_ARCH not referenced"
+        exit 1
+    fi
+    
+    QEMU_USER_STATIC_DOWNLOAD_URL="https://github.com/multiarch/qemu-user-static/releases/download"
+    QEMU_USER_STATIC_LATEST_TAG=$(curl -s https://api.github.com/repos/multiarch/qemu-user-static/tags \
+        | grep 'name.*v[0-9]' \
+        | head -n 1 \
+        | cut -d '"' -f 4)
 
-[ "${BUILD_ARCH}" == "Dockerfile" ] && \
-    { echo 'qemu-user-static: Download not required for current arch'; exit 0; }
+    curl -SL "${QEMU_USER_STATIC_DOWNLOAD_URL}/${QEMU_USER_STATIC_LATEST_TAG}/x86_64_qemu-${QEMU_USER_STATIC_ARCH}-static.tar.gz" \
+        | tar xzv
+done
 
-QEMU_USER_STATIC_ARCH=$([ "${BUILD_ARCH}" == "armhf" ] && echo "${BUILD_ARCH::-2}" || echo "${BUILD_ARCH}")
-QEMU_USER_STATIC_DOWNLOAD_URL="https://github.com/multiarch/qemu-user-static/releases/download"
-QEMU_USER_STATIC_LATEST_TAG=$(curl -s https://api.github.com/repos/multiarch/qemu-user-static/tags \
-    | grep 'name.*v[0-9]' \
-    | head -n 1 \
-    | cut -d '"' -f 4)
-
-curl -SL "${QEMU_USER_STATIC_DOWNLOAD_URL}/${QEMU_USER_STATIC_LATEST_TAG}/x86_64_qemu-${QEMU_USER_STATIC_ARCH}-static.tar.gz" \
-    | tar xzv
+exit 0
